//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballDb9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clubs
    {
        public clubs()
        {
            this.gameschedule = new HashSet<gameschedule>();
            this.gameschedule1 = new HashSet<gameschedule>();
            this.players1 = new HashSet<players>();
            this.stadiums1 = new HashSet<stadiums>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Town { get; set; }
        public string Country { get; set; }
        public string Coach { get; set; }
        public Nullable<int> Stadium { get; set; }
        public string Players { get; set; }
    
        public virtual stadiums stadiums { get; set; }
        public virtual ICollection<gameschedule> gameschedule { get; set; }
        public virtual ICollection<gameschedule> gameschedule1 { get; set; }
        public virtual ICollection<players> players1 { get; set; }
        public virtual ICollection<stadiums> stadiums1 { get; set; }
    }
}
